services:
  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      HTTP_SERVER_ADDRESS: ${HTTP_ADDR}
      APP_ENV: ${APP_ENV} 
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      AUTH_USER: ${AUTH_USER}
      AUTH_PASS: ${AUTH_PASS}
    ports:
      - "${APP_PORT}:8080"

  db:
    image: postgres:16.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - db-data:/var/lib/postgresql/data

      
  migrate:
    image: migrate/migrate:v4.17.1
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}?sslmode=disable",
      "up"
    ]
    

volumes:
  db-data:
    

